packages:
  - backend
  - apps/*
  - packages/*

allowBuilds:
  '@clerk/shared': false
  '@scarf/scarf': false
  '@tree-sitter-grammars/tree-sitter-yaml': false
  better-sqlite3: true
  core-js-pure: false
  esbuild: true
  tree-sitter: false
  tree-sitter-json: false
  unrs-resolver: true

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
