/**
 * PostgreSQL database connection via Drizzle ORM.
 * Connection string comes from DATABASE_URL env variable.
 *
 * Note: env loading is the host's responsibility (Next.js auto-loads .env.local;
 * tsx scripts use dotenv/config CLI flag) — this module no longer imports dotenv.
 */
import { drizzle } from "drizzle-orm/node-postgres";
import { Pool } from "pg";
import * as schema from "./schema";

const pool = new Pool({
  connectionString: process.env.DATABASE_URL ?? "postgres://postgres:postgres@localhost:55432/googenie",
  max: 10,
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 5000,
});

export const db = drizzle(pool, { schema });
export { schema };

/**
 * Run additive migrations (ALTER TABLE IF NOT EXISTS) so the live DB
 * stays in sync with schema.ts without requiring a full migration tool.
 * Safe to call on every startup — all statements are idempotent.
 */
export async function runStartupMigrations(): Promise<void> {
  const client = await pool.connect();
  try {
    await client.query(`
      ALTER TABLE users
        ADD COLUMN IF NOT EXISTS clerk_user_id VARCHAR(128),
        ADD COLUMN IF NOT EXISTS password_hash TEXT,
        ADD COLUMN IF NOT EXISTS settings JSONB NOT NULL DEFAULT '{}'::jsonb;

      CREATE INDEX IF NOT EXISTS users_clerk_user_id_idx ON users(clerk_user_id);

      -- Ensure all three role-based tenants exist.
      -- super_admin → dev-admin | manager_admin → dev-teachers | user → dev-students
      INSERT INTO tenants (id, name) VALUES
        ('dev-admin',    'GooGenie Admins'),
        ('dev-teachers', 'GooGenie Teachers'),
        ('dev-students', 'GooGenie Students')
      ON CONFLICT (id) DO NOTHING;

      -- Feature-access request inbox (idempotent create).
      CREATE TABLE IF NOT EXISTS feature_requests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id VARCHAR(64) NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        requester_user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        target_manager_user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        feature_key VARCHAR(64) NOT NULL,
        status VARCHAR(16) NOT NULL DEFAULT 'pending',
        reason TEXT,
        decided_by_user_id VARCHAR(64),
        decided_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE INDEX IF NOT EXISTS feature_requests_target_status_idx
        ON feature_requests(target_manager_user_id, status);

      CREATE INDEX IF NOT EXISTS feature_requests_requester_idx
        ON feature_requests(requester_user_id);
    `);

    // pgvector extension for semantic email search.
    // Best-effort — if extension not allowed (some managed DBs), search-emails
    // endpoint will degrade to "embeddings_available: false".
    try {
      await client.query(`CREATE EXTENSION IF NOT EXISTS vector;`);
      // Drop table if it was created with the old 1536-dim OpenAI embeddings —
      // Mistral mistral-embed outputs 1024-dim. Embeddings are a rebuildable cache.
      await client.query(`
        DO $$ BEGIN
          IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'email_embeddings'
              AND column_name = 'embedding'
              AND data_type = 'USER-DEFINED'
          ) AND EXISTS (
            SELECT 1 FROM pg_attribute a
              JOIN pg_class c ON c.oid = a.attrelid
              JOIN pg_type t ON t.oid = a.atttypid
             WHERE c.relname = 'email_embeddings'
               AND a.attname = 'embedding'
               AND t.typmod = 1540
          ) THEN
            DROP TABLE email_embeddings;
          END IF;
        END $$;
      `);
      await client.query(`
        CREATE TABLE IF NOT EXISTS email_embeddings (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          thread_id VARCHAR(128) NOT NULL,
          subject TEXT,
          snippet TEXT,
          from_addr TEXT,
          content_hash CHAR(64) NOT NULL,
          embedding vector(1024),
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          UNIQUE(user_id, thread_id)
        );
      `);
      await client.query(`
        CREATE INDEX IF NOT EXISTS email_embeddings_user_idx ON email_embeddings(user_id);
      `);
      // IVF-Flat index for fast cosine similarity (rebuild on growth — fine for hackathon scale)
      await client.query(`
        CREATE INDEX IF NOT EXISTS email_embeddings_vec_idx
          ON email_embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
      `);
    } catch (err) {
      console.warn("[db] pgvector setup skipped:", (err as Error).message);
    }

    // Corsair token store (Phase 8). Tables are created idempotently here so
    // setupCorsair() can run on first boot without a separate migration step.
    // Schema mirrors backend/node_modules/corsair/dist/db.d.ts CorsairKyselyDatabase.
    try {
      await client.query(`
        CREATE TABLE IF NOT EXISTS corsair_integrations (
          id TEXT PRIMARY KEY,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          name TEXT NOT NULL,
          config JSONB,
          dek TEXT
        );

        CREATE TABLE IF NOT EXISTS corsair_accounts (
          id TEXT PRIMARY KEY,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          tenant_id TEXT NOT NULL,
          integration_id TEXT NOT NULL,
          config JSONB,
          dek TEXT
        );
        CREATE INDEX IF NOT EXISTS corsair_accounts_tenant_idx
          ON corsair_accounts(tenant_id, integration_id);

        CREATE TABLE IF NOT EXISTS corsair_entities (
          id TEXT PRIMARY KEY,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          account_id TEXT NOT NULL,
          entity_id TEXT NOT NULL,
          entity_type TEXT NOT NULL,
          version TEXT NOT NULL,
          data JSONB
        );
        CREATE INDEX IF NOT EXISTS corsair_entities_account_idx
          ON corsair_entities(account_id, entity_type, entity_id);

        CREATE TABLE IF NOT EXISTS corsair_events (
          id TEXT PRIMARY KEY,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          account_id TEXT NOT NULL,
          event_type TEXT NOT NULL,
          payload JSONB,
          status TEXT
        );
        CREATE INDEX IF NOT EXISTS corsair_events_account_idx
          ON corsair_events(account_id, event_type);

        CREATE TABLE IF NOT EXISTS corsair_permissions (
          id TEXT PRIMARY KEY,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          token TEXT NOT NULL,
          plugin TEXT NOT NULL,
          endpoint TEXT NOT NULL,
          args TEXT NOT NULL,
          tenant_id TEXT NOT NULL,
          status TEXT NOT NULL DEFAULT 'pending',
          expires_at TEXT NOT NULL,
          error TEXT
        );
        CREATE INDEX IF NOT EXISTS corsair_permissions_token_idx
          ON corsair_permissions(token);
      `);
    } catch (err) {
      console.warn("[db] corsair table setup skipped:", (err as Error).message);
    }

    // ── Superhuman-style features: scheduled emails + public booking links ──
    await client.query(`
      CREATE TABLE IF NOT EXISTS scheduled_emails (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        tenant_id VARCHAR(64) NOT NULL,
        to_addr TEXT NOT NULL,
        subject TEXT NOT NULL,
        body TEXT NOT NULL,
        send_at TIMESTAMPTZ NOT NULL,
        /** queued | sent | cancelled | failed */
        status VARCHAR(16) NOT NULL DEFAULT 'queued',
        /** "undo" for 10s undo-send queue, "scheduled" for explicit send-later */
        kind VARCHAR(16) NOT NULL DEFAULT 'undo',
        sent_message_id TEXT,
        error TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
      CREATE INDEX IF NOT EXISTS scheduled_emails_poller_idx
        ON scheduled_emails(status, send_at);
      CREATE INDEX IF NOT EXISTS scheduled_emails_user_idx
        ON scheduled_emails(user_id, status, send_at);

      CREATE TABLE IF NOT EXISTS booking_links (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        slug VARCHAR(64) NOT NULL UNIQUE,
        title TEXT NOT NULL DEFAULT 'Book a meeting',
        duration_minutes INT NOT NULL DEFAULT 30,
        /** number of business days ahead to expose slots */
        days_ahead INT NOT NULL DEFAULT 14,
        /** UTC hours start..end in {start, end} JSON, e.g. {"start":9,"end":18} */
        business_hours JSONB NOT NULL DEFAULT '{"start":9,"end":18}'::jsonb,
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
      CREATE INDEX IF NOT EXISTS booking_links_user_idx ON booking_links(user_id);

      -- Feature C1 — AI-extracted tasks from email bodies.
      CREATE TABLE IF NOT EXISTS tasks (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        tenant_id VARCHAR(64) NOT NULL,
        thread_id VARCHAR(128) NOT NULL,
        title TEXT NOT NULL,
        sender_email TEXT,
        deadline TIMESTAMPTZ,
        priority VARCHAR(8) NOT NULL DEFAULT 'normal',
        status VARCHAR(16) NOT NULL DEFAULT 'open',
        snippet TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
      CREATE INDEX IF NOT EXISTS tasks_user_idx ON tasks(user_id, status, deadline);
      CREATE INDEX IF NOT EXISTS tasks_thread_idx ON tasks(user_id, thread_id);
    `);
  } finally {
    client.release();
  }
}
