/**
 * PostgreSQL database connection via Drizzle ORM.
 * Connection string comes from DATABASE_URL env variable.
 */
import "dotenv/config";
import { drizzle } from "drizzle-orm/node-postgres";
import { Pool } from "pg";
import * as schema from "./schema.js";

const pool = new Pool({
  connectionString: process.env.DATABASE_URL ?? "postgres://postgres:postgres@localhost:55432/googenie",
  max: 10,
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 5000,
});

export const db = drizzle(pool, { schema });
export { schema };

/**
 * Run additive migrations (ALTER TABLE IF NOT EXISTS) so the live DB
 * stays in sync with schema.ts without requiring a full migration tool.
 * Safe to call on every startup — all statements are idempotent.
 */
export async function runStartupMigrations(): Promise<void> {
  const client = await pool.connect();
  try {
    await client.query(`
      ALTER TABLE users
        ADD COLUMN IF NOT EXISTS clerk_user_id VARCHAR(128),
        ADD COLUMN IF NOT EXISTS password_hash TEXT;

      CREATE INDEX IF NOT EXISTS users_clerk_user_id_idx ON users(clerk_user_id);

      -- Ensure all three role-based tenants exist.
      -- super_admin → dev-admin | manager_admin → dev-teachers | user → dev-students
      INSERT INTO tenants (id, name) VALUES
        ('dev-admin',    'GooGenie Admins'),
        ('dev-teachers', 'GooGenie Teachers'),
        ('dev-students', 'GooGenie Students')
      ON CONFLICT (id) DO NOTHING;

      -- Feature-access request inbox (idempotent create).
      CREATE TABLE IF NOT EXISTS feature_requests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id VARCHAR(64) NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
        requester_user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        target_manager_user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        feature_key VARCHAR(64) NOT NULL,
        status VARCHAR(16) NOT NULL DEFAULT 'pending',
        reason TEXT,
        decided_by_user_id VARCHAR(64),
        decided_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE INDEX IF NOT EXISTS feature_requests_target_status_idx
        ON feature_requests(target_manager_user_id, status);

      CREATE INDEX IF NOT EXISTS feature_requests_requester_idx
        ON feature_requests(requester_user_id);
    `);

    // pgvector extension for semantic email search.
    // Best-effort — if extension not allowed (some managed DBs), search-emails
    // endpoint will degrade to "embeddings_available: false".
    try {
      await client.query(`CREATE EXTENSION IF NOT EXISTS vector;`);
      // Drop table if it was created with the old 1536-dim OpenAI embeddings —
      // Mistral mistral-embed outputs 1024-dim. Embeddings are a rebuildable cache.
      await client.query(`
        DO $$ BEGIN
          IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'email_embeddings'
              AND column_name = 'embedding'
              AND data_type = 'USER-DEFINED'
          ) AND EXISTS (
            SELECT 1 FROM pg_attribute a
              JOIN pg_class c ON c.oid = a.attrelid
              JOIN pg_type t ON t.oid = a.atttypid
             WHERE c.relname = 'email_embeddings'
               AND a.attname = 'embedding'
               AND t.typmod = 1540
          ) THEN
            DROP TABLE email_embeddings;
          END IF;
        END $$;
      `);
      await client.query(`
        CREATE TABLE IF NOT EXISTS email_embeddings (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          thread_id VARCHAR(128) NOT NULL,
          subject TEXT,
          snippet TEXT,
          from_addr TEXT,
          content_hash CHAR(64) NOT NULL,
          embedding vector(1024),
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          UNIQUE(user_id, thread_id)
        );
      `);
      await client.query(`
        CREATE INDEX IF NOT EXISTS email_embeddings_user_idx ON email_embeddings(user_id);
      `);
      // IVF-Flat index for fast cosine similarity (rebuild on growth — fine for hackathon scale)
      await client.query(`
        CREATE INDEX IF NOT EXISTS email_embeddings_vec_idx
          ON email_embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
      `);
    } catch (err) {
      console.warn("[db] pgvector setup skipped:", (err as Error).message);
    }
  } finally {
    client.release();
  }
}
